services:
  authentik:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: authentik
    image: ghcr.io/goauthentik/server:2025.8.1
    profiles: [ "reverse-proxy", "all" ]
    command: server
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__NAME: $AUTHENTIK_DBNAME
      AUTHENTIK_POSTGRESQL__PASSWORD: $AUTHENTIK_DBPASS
      AUTHENTIK_POSTGRESQL__USER: $AUTHENTIK_DBUSER
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_SECRET_KEY: $AUTHENTIK_SECRET
    volumes:
      - $CONF_DIR/authentik/media:/media
      - $CONF_DIR/authentik/custom-templates:/templates
    expose:
      - 9000
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9000/-/health/ready/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authentik-rtr.tls=true"
      - "traefik.http.routers.authentik-rtr.entrypoints=websecure"
      - "traefik.http.routers.authentik-rtr.rule=Host(`authentik.$DOMAINNAME_1`)"
      - "traefik.http.routers.authentik-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.authentik-rtr.service=authentik-svc"
      - "traefik.http.services.authentik-svc.loadbalancer.server.port=9000"

  authentik-worker:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:2025.8.1
    profiles: [ "reverse-proxy", "all" ]
    user: root
    command: worker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgres
      AUTHENTIK_POSTGRESQL__NAME: $AUTHENTIK_DBNAME
      AUTHENTIK_POSTGRESQL__PASSWORD: $AUTHENTIK_DBPASS
      AUTHENTIK_POSTGRESQL__USER: $AUTHENTIK_DBUSER
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_SECRET_KEY: $AUTHENTIK_SECRET
    healthcheck:
      test: [ "CMD-SHELL", "ak healthcheck || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONF_DIR/authentik/certs:/certs
      - $CONF_DIR/authentik/media:/media
      - $CONF_DIR/authentik/custom-templates:/templates
