services:
  adminer:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: adminer
    image: adminer:5.4.2-standalone
    profiles: [ "database", "infra", "all" ]
    expose:
      - 8080
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8080 || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer-rtr.tls=true"
      - "traefik.http.routers.adminer-rtr.entrypoints=websecure"
      - "traefik.http.routers.adminer-rtr.rule=Host(`adminer.$DOMAINNAME_1`)"
      - "traefik.http.routers.adminer-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.adminer-rtr.service=adminer-svc"
      - "traefik.http.services.adminer-svc.loadbalancer.server.port=8080"
