services:
  mongo:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: mongo
    image: mongo:8.2.6
    profiles: [ "database", "infra", "all" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_DBUSER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_DBPASS
    volumes:
      - $CONF_DIR/mongo/db:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval \"db.runCommand('ping').ok\" || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongo-express:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: mongo-express
    image: mongo-express
    profiles: [ "database", "all" ]
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: $MONGO_DBUSER
      ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_DBPASS
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_DBUSER:$MONGO_DBPASS@mongo:27017/
    expose:
      - 8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express-rtr.tls=true"
      - "traefik.http.routers.mongo-express-rtr.entrypoints=websecure"
      - "traefik.http.routers.mongo-express-rtr.rule=Host(`mongo.$DOMAINNAME_1`)"
      - "traefik.http.routers.mongo-express-rtr.middlewares=chain-authentik@file"
      - "traefik.http.routers.mongo-express-rtr.service=mongo-express-svc"
      - "traefik.http.services.mongo-express-svc.loadbalancer.server.port=8081"
