services:
  s3:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: s3
    image: zenko/cloudserver:latest-7.10.19
    profiles: [ "database", "infra", "all" ]
    environment:
      S3METADATAPATH: /var/lib/s3/meta
      S3DATAPATH: /var/lib/s3/data
      REMOTE_MANAGEMENT_DISABLE: true
      HOST_NAMES: "s3"
    volumes:
      - $CONF_DIR/s3/meta:/var/lib/s3/meta
      - $CONF_DIR/s3/data:/var/lib/s3/data
    ports:
      - 10.10.0.10:6379:6379