services:
  redis:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: redis
    image: redis:7.4-alpine
    profiles: [ "database", "infra", "all" ]
    volumes:
      - $CONF_DIR/redis/data:/data
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      timeout: 3s
