http:
  routers:
    budget-tracker-demo-rtr:
      rule: 'Host(`budget-demo.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: budget-tracker-demo-svc
      tls:
        certResolver: dns-cloudflare
  services:
    budget-tracker-demo-svc:
      loadBalancer:
        servers:
          - url: 'http://{{env "LXC_PRODUCTIVITY_IP"}}:8091'