http:
  routers:
    seerr-rtr:
      rule: 'Host(`request.{{env "DOMAINNAME_1"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: seerr-svc
      tls:
        certResolver: dns-cloudflare
  services:
    seerr-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_MEDIA_IP"}}:5055"
