http:
  routers:
    jellyfin-rtr:
      rule: 'Host(`jellyfin.{{env "DOMAINNAME_1"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: jellyfin-svc
      tls:
        certResolver: dns-cloudflare
  services:
    jellyfin-svc:
      loadBalancer:
        servers:
          - url: 'http://{{env "LXC_MEDIA_IP"}}:8096'