http:
  routers:
    jackett-rtr:
      rule: 'Host(`jacket.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-authentik
      service: jackett-svc
      tls:
        certResolver: dns-cloudflare
  services:
    jackett-svc:
      loadBalancer:
        servers:
          - url: 'http://{{env "LXC_MEDIA_IP"}}:9117'