networks:
  t3_proxy:
    name: t3_proxy
    driver: bridge

include:
  - compose/network/compose.unifi.yml
  - compose/network/compose.unifi-os.yml
  - compose/network/compose.pihole.yml
  - compose/monitoring/compose.cadvisor.yml
