http:
  middlewares:
    chain-vgz-whitelist:
      chain:
        middlewares:
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-cloudflare-whitelist
          - middlewares-local-whitelist
          - middlewares-vgz-whitelist