services:      
  chat-ui:
    container_name: chat-ui
    image: ghcr.io/huggingface/chat-ui-db:0.9.4
    restart: unless-stopped
    profiles: ["other", "all"]
    networks:
      - t3_proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MONGODB_URL=mongodb://$MONGO_DBUSER:$MONGO_DBPASS@mongo:27017/
    volumes:
      - $CONF_DIR/chat-ui/data:/data
      - $CONF_DIR/chat-ui/.env.local:/app/.env.local
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat-rtr.tls=true"
      - "traefik.http.routers.chat-rtr.entrypoints=websecure"
      - "traefik.http.routers.chat-rtr.rule=Host(`chat.$DOMAINNAME_1`)"
      - "traefik.http.routers.chat-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.chat-rtr.service=chat-svc"
      - "traefik.http.services.chat-svc.loadbalancer.server.port=3000"

  
  ollama:
    container_name: ollama
    image: ollama/ollama:0.5.7
    restart: unless-stopped
    profiles: ["other", "all"]
    networks:
      - t3_proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONF_DIR/ollama:/root/.ollama
    expose:
      - 11434