services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.23.16
    restart: unless-stopped
    profiles: ["other", "statistics", "all"]
    networks:
      - t3_proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONF_DIR/uptime-kuma/data:/app/data
    expose:
      - 3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma-rtr.tls=true"
      - "traefik.http.routers.uptime-kuma-rtr.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma-rtr.rule=Host(`uptime.$DOMAINNAME_1`)"
      - "traefik.http.routers.uptime-kuma-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.uptime-kuma-rtr.service=uptime-kuma-svc"
      - "traefik.http.services.uptime-kuma-svc.loadbalancer.server.port=3001"
