services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.7.11
    restart: unless-stopped
    profiles: ["other", "statistics", "all"]
    networks:
      - t3_proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - INFLUXDB_ADMIN_USER=$INFLUXDB_USER
      - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_PASS
    volumes:
      - $CONF_DIR/influxdb/data:/var/lib/influxdb
      - $CONF_DIR/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - $CONF_DIR/influxdb/init:/docker-entrypoint-initdb.d
    expose:
      - 8086
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb-rtr.tls=true"
      - "traefik.http.routers.influxdb-rtr.entrypoints=websecure"
      - "traefik.http.routers.influxdb-rtr.rule=Host(`influxdb.$DOMAINNAME_1`)"
      - "traefik.http.routers.influxdb-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.influxdb-rtr.service=influxdb-svc"
      - "traefik.http.services.influxdb-svc.loadbalancer.server.port=8086"

  telegraf:
    container_name: telegraf
    image: telegraf:1.33.2
    restart: unless-stopped
    profiles: ["other", "statistics", "all"]
    networks:
      - t3_proxy
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    volumes:
      - $CONF_DIR/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  chronograf:
    container_name: chronograf
    image: chronograf:1.10.5
    restart: unless-stopped
    profiles: ["other", "statistics", "all"]
    networks:
      - t3_proxy
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=$INFLUXDB_USER
      - INFLUXDB_PASSWORD=$INFLUXDB_PASS
    expose:
      - 8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chronograf-rtr.tls=true"
      - "traefik.http.routers.chronograf-rtr.entrypoints=websecure"
      - "traefik.http.routers.chronograf-rtr.rule=Host(`chronograf.$DOMAINNAME_1`)"
      - "traefik.http.routers.chronograf-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.chronograf-rtr.service=chronograf-svc"
      - "traefik.http.services.chronograf-svc.loadbalancer.server.port=8888"
