services:
  postgres:
    container_name: postgres
    image: postgres:16.4
    restart: unless-stopped
    profiles: ["other", "database", "all"]
    networks:
      - t3_proxy
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
      - POSTGRES_PASSWORD=$PSQL_DBPASS
    volumes:
      - $CONF_DIR/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    shm_size: 256M