services:
  immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:v1.129.0
    restart: unless-stopped
    profiles: ["other", "all"]
    healthcheck:
      disable: false
    networks:
      - t3_proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    env_file:
      - $CONF_DIR/immich/.env
    volumes:
      - $PHOTOS_DIR/library:/usr/src/app/upload
      - $CONF_DIR/immich/external:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 2283
    ports:
      - 2283:2283
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich-rtr.tls=true"
      - "traefik.http.routers.immich-rtr.entrypoints=websecure"
      - "traefik.http.routers.immich-rtr.rule=Host(`photos.$DOMAINNAME_1`) || Host(`immich.$DOMAINNAME_1`)"
      - "traefik.http.routers.immich-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.immich-rtr.service=immich-svc"
      - "traefik.http.services.immich-svc.loadbalancer.server.port=2283"

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.129.0
    restart: unless-stopped
    profiles: ["other", "all"]
    healthcheck:
      disable: false
    networks:
      - t3_proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    env_file:
      - $CONF_DIR/immich/.env
    volumes:
      - $CONF_DIR/immich/cache:/cache
