services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2024.10.3"
    restart: unless-stopped
    profiles: ["other", "all"]
    networks:
      - t3_proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $CONF_DIR/homeassistant/config:/config
      - $CONF_DIR/homeassistant/images:/images
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8123
    ports:
      - 21064:21064 # HASS Bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant-rtr.tls=true"
      - "traefik.http.routers.homeassistant-rtr.entrypoints=websecure"
      - "traefik.http.routers.homeassistant-rtr.rule=Host(`home.$DOMAINNAME_1`)"
      - "traefik.http.routers.homeassistant-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.homeassistant-rtr.service=homeassistant-svc"
      - "traefik.http.services.homeassistant-svc.loadbalancer.server.port=8123"
