networks:
  t3_proxy:
    name: t3_proxy
    driver: bridge

include:
  - compose/productivity/compose.immich.yml
  - compose/productivity/compose.paperless.yml
  - compose/productivity/compose.nextcloud.yml
  - compose/productivity/compose.backrest.yml
