networks:
  t3_proxy:
    name: t3_proxy
    driver: bridge

include:
  - compose/productivity/compose.immich.yml
  - compose/productivity/compose.firefly.yml
  - compose/productivity/compose.paperless.yml
  - compose/productivity/compose.nextcloud.yml
  - compose/productivity/compose.backrest.yml
  - compose/utilities/compose.it-tools.yml
  - compose/utilities/compose.omni-tools.yml
  # - compose/utilities/compose.printer-calculator.yml
  - compose/utilities/compose.spoolman.yml
  - compose/utilities/compose.print-costs.yml
  - compose/monitoring/compose.cadvisor.yml
