http:
  routers:
    {{ range $i := until 25 }}
    {{ \(shopNum := printf "\d" (add\)i 1) }}
    juice-shop-{{ $shopNum }}-rtr:
      rule: 'Host(`shop{{ $shopNum }}.{{ env "DOMAINNAME_2" }}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-authentik
      service: juice-shop-{{ $shopNum }}-svc
      tls:
        certResolver: dns-cloudflare
    {{ end }}

  services:
    {{ range $i := until 25 }}
    {{ \(shopNum := printf "\d" (add\)i 1) }}
    {{ \(port := add\)i 3000 }}
    juice-shop-{{ $shopNum }}-svc:
      loadBalancer:
        servers:
          - url: 'http://{{ env "LXC_JUICE_SHOP_IP" }}:{{ $port }}'
    {{ end }}
