http:
  routers:
    juice-shop-01-rtr:
      rule: 'Host(`shop01.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-01-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-02-rtr:
      rule: 'Host(`shop02.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-02-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-03-rtr:
      rule: 'Host(`shop03.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-03-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-04-rtr:
      rule: 'Host(`shop04.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-04-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-05-rtr:
      rule: 'Host(`shop05.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-05-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-06-rtr:
      rule: 'Host(`shop06.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-06-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-07-rtr:
      rule: 'Host(`shop07.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-07-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-08-rtr:
      rule: 'Host(`shop08.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-08-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-09-rtr:
      rule: 'Host(`shop09.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-09-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-10-rtr:
      rule: 'Host(`shop10.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-10-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-11-rtr:
      rule: 'Host(`shop11.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-11-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-12-rtr:
      rule: 'Host(`shop12.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-12-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-13-rtr:
      rule: 'Host(`shop13.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-13-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-14-rtr:
      rule: 'Host(`shop14.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-14-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-15-rtr:
      rule: 'Host(`shop15.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-15-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-16-rtr:
      rule: 'Host(`shop16.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-16-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-17-rtr:
      rule: 'Host(`shop17.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-17-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-18-rtr:
      rule: 'Host(`shop18.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-18-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-19-rtr:
      rule: 'Host(`shop19.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-19-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-20-rtr:
      rule: 'Host(`shop20.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-20-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-21-rtr:
      rule: 'Host(`shop21.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-21-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-22-rtr:
      rule: 'Host(`shop22.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-22-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-23-rtr:
      rule: 'Host(`shop23.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-23-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-24-rtr:
      rule: 'Host(`shop24.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-24-svc
      tls:
        certResolver: dns-cloudflare
    juice-shop-25-rtr:
      rule: 'Host(`shop25.{{env "DOMAINNAME_2"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-no-auth
      service: juice-shop-25-svc
      tls:
        certResolver: dns-cloudflare
  services:
    juice-shop-01-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3000"
    juice-shop-02-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3001"
    juice-shop-03-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3002"
    juice-shop-04-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3003"
    juice-shop-05-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3004"
    juice-shop-06-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3005"
    juice-shop-07-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3006"
    juice-shop-08-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3007"
    juice-shop-09-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3008"
    juice-shop-10-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3009"
    juice-shop-11-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3010"
    juice-shop-12-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3011"
    juice-shop-13-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3012"
    juice-shop-14-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3013"
    juice-shop-15-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3014"
    juice-shop-16-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3015"
    juice-shop-17-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3016"
    juice-shop-18-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3017"
    juice-shop-19-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3018"
    juice-shop-20-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3019"
    juice-shop-21-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3020"
    juice-shop-22-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3021"
    juice-shop-23-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3022"
    juice-shop-24-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3023"
    juice-shop-25-svc:
      loadBalancer:
        servers:
          - url: "http://{{env "LXC_JUICE_SHOP_IP"}}:3024"
