services:
  unifi-network-application:
    extends:
      file: ../fragments/common-service.yml
      service: common-lsio
    container_name: unifi-network-application
    image: lscr.io/linuxserver/unifi-network-application:10.1.89
    profiles: [ "network", "all" ]
    environment:
      MONGO_USER: $UNIFI_DBUSER
      MONGO_PASS: $UNIFI_DBPASS
      MONGO_HOST: 10.10.0.10
      MONGO_PORT: 27017
      MONGO_DBNAME: $UNIFI_DBNAME
    volumes:
      - $CONF_DIR/unifi/config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8843:8843 # optional
      - 8880:8880 # optional
      - 6789:6789 # optional
      - 5514:5514/udp # optional
    healthcheck:
      test: [ "CMD", "curl", "-fsSo", "/dev/null", "--insecure", "https://localhost:8443/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
