services:
  jackett:
    extends:
      file: ../fragments/common-service.yml
      service: common-lsio
    container_name: jackett
    image: lscr.io/linuxserver/jackett:0.24.1879
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/jackett/config:/config
    ports:
      - $LXC_IP:9117:9117
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9117/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
