services:
  lingarr:
    container_name: lingarr
    image: lingarr/lingarr:1.0.3
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - t3_proxy
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
      - ASPNETCORE_URLS=http://+:9876
    volumes:
      - $CONF_DIR/lingarr/config:/app/config
      - $MEDIA_DIR/movies:/movies
      - $MEDIA_DIR/tv-shows:/tv
    expose:
      - 9876
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lingarr-rtr.tls=true"
      - "traefik.http.routers.lingarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.lingarr-rtr.rule=Host(`lingarr.$DOMAINNAME_1`)"
      - "traefik.http.routers.lingarr-rtr.middlewares=chain-authentik@file"
      - "traefik.http.routers.lingarr-rtr.service=lingarr-svc"
      - "traefik.http.services.lingarr-svc.loadbalancer.server.port=9876"