services:
  agregarr:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: agregarr
    image: agregarr/agregarr:v2.3.0
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/agregarr/config:/app/config
      - $MEDIA_DIR/movies:/data/movies
      - $MEDIA_DIR/tv-shows:/data/tv
    ports:
      - 7171:7171
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7171/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
