services:
  profilarr:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: profilarr
    image: santiagosayshey/profilarr:v1.1.5
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/profilarr/config:/config
    ports:
      - $LXC_IP:6868:6868
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:6868/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
