services:
  radarr:
    extends:
      file: ../fragments/common-service.yml
      service: common-lsio
    container_name: radarr
    image: linuxserver/radarr:6.1.1
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/radarr/config:/config
      - $MEDIA_DIR:/media
      - $DOWNLOAD_DIR:/data
      - $DOWNLOAD_DIR:/downloads
    ports:
      - 7878:7878
    healthcheck:
      test: [ "CMD", "curl", "-fsSo", "/dev/null", "http://localhost:7878/api/v3/health?apiKey=$RADARR_API_KEY" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  radarr-4k:
    extends:
      file: ../fragments/common-service.yml
      service: common-lsio
    container_name: radarr-4k
    image: linuxserver/radarr:6.1.1
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/radarr-4k/config:/config
      - $MEDIA_DIR:/media
      - $DOWNLOAD_DIR:/data
      - $DOWNLOAD_DIR:/downloads
    ports:
      - 7879:7878
    healthcheck:
      test: [ "CMD", "curl", "-fsSo", "/dev/null", "http://localhost:7878/api/v3/health?apiKey=$RADARR_4K_API_KEY" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
