services:
  bazarr:
    extends:
      file: ../fragments/common-service.yml
      service: common-lsio
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:1.5.3
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/bazarr/config:/config
      - $MEDIA_DIR/movies:/movies
      - $MEDIA_DIR/tv-shows:/tv
    ports:
      - 6767:6767
    healthcheck:
      test: [ "CMD", "curl", "-fsSo", "/dev/null", "http://localhost:6767/api/system/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
