services:
  wizarr:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:v2026.7.1
    profiles: [ "media", "all" ]
    environment:
      DISABLE_BUILTIN_AUTH: false
    volumes:
      - $CONF_DIR/wizarr/data:/data
    ports:
      - 5690:5690
