services:
  jellyfin:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: jellyfin
    image: jellyfin/jellyfin:10.11.8
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/jellyfin/config:/config
      - $CONF_DIR/jellyfin/cache:/cache
      - $MEDIA_DIR/appdata/jellyfin/metadata:/config/metadata
      - $MEDIA_DIR/appdata/jellyfin/trickplay:/config/data/trickplay
      - $MEDIA_DIR:/media
    ports:
      - 10.10.0.20:8096:8096/tcp
      - 7359:7359/udp
    healthcheck:
      test: [ "CMD", "curl", "-fsSo", "/dev/null", "http://localhost:8096/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    devices:
      - /dev/dri:/dev/dri
