services:
  pinchflat:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: pinchflat
    image: ghcr.io/kieraneglin/pinchflat:latest
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/pinchflat/config:/config
      - $MEDIA_DIR/youtube:/downloads
    ports:
      - $LXC_IP:8945:8945
