services:
  plex-rewind:
    container_name: plex-rewind
    image: ghcr.io/raunot/plex-rewind:4.9.1
    restart: unless-stopped
    profiles: [ "media", "all" ]
    networks:
      - t3_proxy
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
      - NEXTAUTH_SECRET=$PLEX_REWIND_SECRET
      - NEXTAUTH_URL=http://192.168.2.201:8383
      - NEXT_PUBLIC_SITE_URL=http://192.168.2.201:8383
    volumes:
      - $CONF_DIR/plex-rewind/config:/app/config
    expose:
      - 8383
    ports:
      - 8383:8383
