services:
  maintainerr:
    container_name: maintainerr
    image: ghcr.io/maintainerr/maintainerr:2.20.0
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - t3_proxy
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    volumes:
      - $CONF_DIR/maintainerr/data:/opt/data
    expose:
      - 6246
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maintainerr-rtr.entrypoints=websecure"
      - "traefik.http.routers.maintainerr-rtr.rule=Host(`maintainerr.$DOMAINNAME_1`)"
      - "traefik.http.routers.maintainerr-rtr.middlewares=chain-authentik@file"
      - "traefik.http.routers.maintainerr-rtr.service=maintainerr-svc"
      - "traefik.http.services.maintainerr-svc.loadbalancer.server.port=6246"
