services:
  huntarr:
    container_name: huntarr
    image: ghcr.io/plexguide/huntarr:8.2.6
    restart: unless-stopped
    profiles: [ "media", "all" ]
    networks:
      - t3_proxy
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    volumes:
      - $CONF_DIR/huntarr/config:/config
    expose:
      - 9705
    ports:
      - 9705:9705
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9705/health" ]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huntarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.huntarr-rtr.rule=Host(`huntarr.$DOMAINNAME_1`)"
      - "traefik.http.routers.huntarr-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.huntarr-rtr.service=huntarr-svc"
      - "traefik.http.services.huntarr-svc.loadbalancer.server.port=9705"
