services:
  sabnzbd:
    extends:
      file: ../fragments/common-service.yml
      service: common-lsio
    container_name: sabnzbd
    image: linuxserver/sabnzbd:4.5.5
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/sabnzbd/config:/config
      - $DOWNLOAD_DIR:/downloads
    ports:
      - 8082:8080
    healthcheck:
      test: [ "CMD", "curl", "-fsSo", "/dev/null", "http://localhost:8080/api?mode=version&output=json&apikey=$SABNZBD_API_KEY" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
