services:
  tautulli:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: tautulli
    image: tautulli/tautulli:v2.16.0
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/tautulli/config:/config
      - $CONF_DIR/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 8181:8181
    healthcheck:
      test: [ "CMD", "curl", "-fsSo", "/dev/null", "http://localhost:8181/status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s