services:
  prowlarr:
    extends:
      file: ../fragments/common-service.yml
      service: common-lsio
    container_name: prowlarr
    image: linuxserver/prowlarr:2.3.5
    profiles: [ "media", "all" ]
    volumes:
      - $CONF_DIR/prowlarr/config:/config
      - $DOWNLOAD_DIR:/data
      - $DOWNLOAD_DIR:/downloads
    ports:
      - 9696:9696
    healthcheck:
      test: [ "CMD", "curl", "-fsSo", "/dev/null", "http://localhost:9696/api/v1/system/status?apikey=$PROWLARR_API_KEY" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
