http:
  middlewares:
    middlewares-vgz-whitelist:
      ipAllowList:
        sourceRange:
          - "10.10.0.70/24"
          - "192.168.2.0/24"
          - "127.0.0.1/32"
          - "172.17.0.1/16"
          - "172.18.0.1/16"
          - "2a02:a442:15a5::/64"
          - "77.161.9.198/32"
        rejectStatusCode: 404