http:
  routers:
    spoolman-rtr:
      rule: 'Host(`spoolman.{{env "DOMAINNAME_1"}}`)'
      entryPoints:
        - websecure
      middlewares:
        - chain-authentik
      service: spoolman-svc
      tls:
        certResolver: dns-cloudflare
  services:
    spoolman-svc:
      loadBalancer:
        servers:
          - url: 'http://{{env "LXC_PRODUCTIVITY_IP"}}:8001'
