networks:
  t3_proxy:
    name: t3_proxy
    driver: bridge

include:
  - compose/productivity/compose.juice-shop.yml
  - compose/productivity/compose.cadvisor.yml
  - compose/monitoring/compose.alloy.yml
  - compose/utilities/compose.portainer-agent.yml
