services:
  alertmanager:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: alertmanager
    image: prom/alertmanager:v0.34.0
    profiles: [ "monitoring", "all" ]
    command:
      - --config.file=/config/alertmanager.yml
    volumes:
      - $CONF_DIR/alertmanager/config:/config
      - $CONF_DIR/alertmanager/data:/data
    ports:
      - $LXC_IP:9093:9093
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9093/-/healthy" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
