services:
  promtail:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: promtail
    image: grafana/promtail:3.5.3
    profiles: [ "monitoring", "all" ]
    command: -config.file=/mnt/config/promtail-config.yaml
    links:
      - loki
    volumes:
      - $CONF_DIR/promtail/config:/mnt/config
      - /var/log:/var/log
    ports:
      - 9080:9080
