services:
  grafana:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: grafana
    image: grafana/grafana:11.5.2
    profiles: [ "monitoring", "all" ]
    user: $PUID:$PGID
    security_opt:
      - no-new-privileges:true
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - $CONF_DIR/grafana/data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
