services:
  loki:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: loki
    image: grafana/loki:3.5.3
    profiles: [ "monitoring", "all" ]
    command:
      - -config.file=/mnt/config/loki-config.yaml
    volumes:
      - $CONF_DIR/loki/config:/mnt/config
    ports:
      - 3100:3100
