services:
  prometheus:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: prometheus
    image: prom/prometheus:v3.11.2
    user: $PUID:$PGID
    profiles: [ "monitoring", "all" ]
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.size=25GB
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    volumes:
      - $CONF_DIR/prometheus:/prometheus
      - $CONF_DIR/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 10.10.0.60:9090:9090
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9090/-/healthy" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
