services:
  cadvisor:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    profiles: [ "monitoring", "all" ]
    command:
      - --docker_only=true
      - --housekeeping_interval=15s
      - --disable_metrics=advtcp,app,cpuLoad,cpu_topology,cpuset,disk,diskIO,hugetlb,memory_numa,oom_event,percpu,perf_event,process,referenced_memory,resctrl,sched,tcp,udp
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8888:8080
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
