services:
  cadvisor:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    profiles: [ "monitoring", "all" ]
    command:
      - '--housekeeping_interval=15s'
      - '--docker_only=true'
      - '--disable_metrics=percpu,sched,tcp,udp,disk,diskIO,hugetlb,referenced_memory'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
