services:
  loki:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: loki
    image: grafana/loki:3.7.1
    profiles: [ "monitoring", "all" ]
    command:
      - -config.file=/mnt/config/loki-config.yaml
    volumes:
      - $CONF_DIR/loki/config:/mnt/config
    ports:
      - 3100:3100
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3100/ready" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
