services:
  zigbee2mqtt:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:2.9.1
    profiles: [ "home", "all" ]
    volumes:
      - $CONF_DIR/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
