services:
  mosquitto:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.21
    profiles: [ "home", "all" ]
    volumes:
      - $CONF_DIR/mosquitto/config:/mosquitto/config
      - $CONF_DIR/mosquitto/data:/mosquitto/data
      - $CONF_DIR/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
