services:
  musicassistant:
    extends:
      file: ../fragments/common-service.yml
      service: common-host
    container_name: musicassistant
    image: ghcr.io/music-assistant/server:2.8.2
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    profiles: [ "home", "all" ]
    environment:
      LOG_LEVEL: info
    volumes:
      - $CONF_DIR/musicassistant/data:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8095/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
