services:
  musicassistant:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: musicassistant
    image: ghcr.io/music-assistant/server:2.7.2
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    profiles: [ "home", "all" ]
    network_mode: host
    environment:
      LOG_LEVEL: info
    volumes:
      - $CONF_DIR/musicassistant/data:/data
    labels:
      - "diun.enable=true"
