services:
  frigate:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.17.0
    profiles: [ "home", "all" ]
    shm_size: 128mb
    devices:
      - /dev/dri:/dev/dri
    environment:
      FRIGATE_RTSP_PASSWORD: $FRIGATE_RTSP_PASSWORD
      LIBVA_DRIVER_NAME: i965
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $CONF_DIR/frigate/openvino-model:/openvino-model
      - $CONF_DIR/frigate/config:/config
      - $NVR_DIR:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - 5001:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:5000/api/stats" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s