services:
  mosquitto:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.22
    profiles: [ "home", "all" ]
    volumes:
      - $CONF_DIR/mosquitto/config:/mosquitto/config
      - $CONF_DIR/mosquitto/data:/mosquitto/data
      - $CONF_DIR/mosquitto/log:/mosquitto/log
    ports:
      - 10.10.0.30:1883:1883
    healthcheck:
      test: [ "CMD-SHELL", "mosquitto_sub -h localhost -t '$$SYS/#' -C 1 -u $MOSQUITTO_USER -P $MOSQUITTO_PASS -W 3 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
