services:
  n8n:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: n8n
    image: n8nio/n8n:2.36.4
    profiles: [ "productivity", "all" ]
    environment:
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - N8N_HOST=n8n.${DOMAINNAME_1}
      - N8N_WEBHOOK_URL=https://n8n.${DOMAINNAME_1}/
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RESTRICT_FILE_ACCESS_TO=/appdata/queue;/archive
    volumes:
      - $CONF_DIR/n8n/data:/home/node/.n8n
      - $CONF_DIR/n8n/queue:/appdata/queue
      - $ARCHIVE_DIR/ChronicleCore:/archive
    ports:
      - 10.10.0.40:5678:5678
