x-juice-shop-resources: &juice-shop-resources
  deploy:
    resources:
      limits:
        cpus: '0.50'
        memory: 256M

services:
  juice-shop-1:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-1
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3000:3000

  juice-shop-2:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-2
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3001:3000

  juice-shop-3:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-3
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3002:3000

  juice-shop-4:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-4
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3003:3000

  juice-shop-5:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-5
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3004:3000

  juice-shop-6:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-6
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3005:3000

  juice-shop-7:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-7
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3006:3000

  juice-shop-8:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-8
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3007:3000

  juice-shop-9:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-9
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3008:3000

  juice-shop-10:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-10
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3009:3000

  juice-shop-11:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-11
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3010:3000

  juice-shop-12:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-12
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3011:3000

  juice-shop-13:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-13
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3012:3000

  juice-shop-14:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-14
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3013:3000

  juice-shop-15:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-15
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3014:3000

  juice-shop-16:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-16
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3015:3000

  juice-shop-17:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-17
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3016:3000

  juice-shop-18:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-18
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3017:3000

  juice-shop-19:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-19
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3018:3000

  juice-shop-20:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-20
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3019:3000

  juice-shop-21:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-21
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3020:3000

  juice-shop-22:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-22
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3021:3000

  juice-shop-23:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-23
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3022:3000

  juice-shop-24:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-24
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3023:3000

  juice-shop-25:
    <<: *juice-shop-resources
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: juice-shop-25
    image: bkimminich/juice-shop:v20.2.0
    profiles: ["productivity", "all"]
    environment:
      NODE_ENV: quiet
    ports:
      - 3024:3000
