services:
  paperless:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:2.14.7
    profiles: [ "productivity", "all" ]
    environment:
      PAPERLESS_REDIS: redis://10.10.0.10:6379
      PAPERLESS_DBHOST: 10.10.0.10
      PAPERLESS_DBNAME: $PAPERLESS_DBNAME
      PAPERLESS_DBUSER: $PAPERLESS_DBUSER
      PAPERLESS_DBPASS: $PAPERLESS_DBPASS
      PAPERLESS_URL: https://paperless.$DOMAINNAME_1
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "APPS": [
              {
                "provider_id": "authentik",
                "name": "Authentik",
                "client_id": "${PAPERLESS_AUTH_CLIENT_ID}",
                "secret": "${PAPERLESS_AUTH_CLIENT_SECRET}",
                "settings": {
                  "server_url": "https://authentik.${DOMAINNAME_1}/application/o/paperless-ngx/.well-known/openid-configuration"
                }
              }
            ],
            "OAUTH_PKCE_ENABLED": "True"
          }
        }
    volumes:
      - $CONF_DIR/paperless/data:/usr/src/paperless/data
      - $DMS_DIR/media:/usr/src/paperless/media
      - $DMS_DIR/consume:/usr/src/paperless/consume
    ports:
      - 8000:8000
    healthcheck:
      test: [ "CMD", "curl", "-fsSo", "/dev/null", "http://localhost:8000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
