services:
  backrest:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: backrest
    image: garethgeorge/backrest:v1.12.1
    profiles: [ "productivity", "all" ]
    environment:
      XDG_CACHE_HOME: /cache
      BACKREST_CONFIG: /config/config.json
      BACKREST_DATA: /data
    volumes:
      - $CONF_DIR/backrest/data:/data
      - $CONF_DIR/backrest/config:/config
      - $CONF_DIR/backrest/cache:/cache
      - $DOCKER_DIR:/docker
      - $MNT_DIR:/mnt
    ports:
      - 9898:9898
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9898/" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
