services:
  chromium:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: chromium
    image: ghcr.io/browserless/chromium:v2.56.3
    profiles: [ "productivity", "all" ]
    environment:
      CONCURRENT: 5
      TOKEN: $CHROMIUM_TOKEN
    ports:
      - 3001:3000
