services:
  printer-calculator:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: printer-calculator
    image: rick043/3d-printer-cost-calculator:latest
    profiles: [ "utilities", "all" ]
    environment:
      DATABASE_URL: postgresql://${PRINTER_CALCULATOR_DBUSER}:${PRINTER_CALCULATOR_DBPASS}@postgres:5432/${PRINTER_CALCULATOR_DBNAME}
      STREAMLIT_SERVER_MAX_UPLOAD_SIZE: 2000
    volumes:
      - $CONF_DIR/3d-printer-cost-calculator/uploads:/app/uploads
    ports:
      - 4569:5000
