services:
  it-tools:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: it-tools
    image: ghcr.io/corentinth/it-tools:2024.10.22-7ca5933
    profiles: [ "utilities", "all" ]
    ports:
      - 8082:80
