services:
  omni-tools:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: omni-tools
    image: iib0011/omni-tools:0.6.0
    profiles: [ "utilities", "all" ]
    ports:
      - $LXC_IP:8083:80
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
