services:
  it-tools:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: it-tools
    image: ghcr.io/corentinth/it-tools:2024.10.22-7ca5933
    profiles: [ "utilities", "all" ]
    ports:
      - $LXC_IP:8082:80
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
