services:
  omni-tools:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: omni-tools
    image: iib0011/omni-tools:0.5.0
    profiles: [ "utilities", "all" ]
    ports:
      - 80:80
