services:
  spoolman:
    extends:
      file: ../fragments/common-service.yml
      service: common
    container_name: spoolman
    image: ghcr.io/donkie/spoolman:0.21.0
    profiles: [ "utilities", "all" ]
    volumes:
      - $CONF_DIR/spoolman/data:/home/app/.local/share/spoolman
    ports:
      - 8000:8000
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8000/api/v1/info" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
